# Generated by Django 6.0.5 on 2026-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_alter_coupon_max_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_remaining",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
