# Generated by Django 6.0.5 on 2026-09-03 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_usage_remaining'),
        ('order', '0027_rename_subtoal_orders_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'user'), name='unique_coupon_per_user'),
        ),
    ]
