# Generated by Django 6.0.5 on 2026-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0005_usercoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_referral_coupon",
            field=models.BooleanField(default=False),
        ),
    ]
