# Generated by Django 6.0.5 on 2026-09-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_coupon_is_referral_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_referral_coupon',
        ),
    ]
