# Generated by Django 6.0.5 on 2026-07-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_ordertrack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("order placed", "Order Placed"),
                    ("shipped", "Shipped"),
                    ("out for delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordertrack",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("order placed", "Order Placed"),
                    ("shipped", "Shipped"),
                    ("out for delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="OrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation",
                        to="order.orders",
                    ),
                ),
            ],
            options={
                "db_table": "order_cancellations",
            },
        ),
    ]
