# Generated by Django 6.0.5 on 2026-07-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_orders_status_alter_ordertrack_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
    ]
