# Generated by Django 6.0.5 on 2026-07-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_orderitemcancellation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemcancellation",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellation",
                to="order.orderitems",
            ),
        ),
    ]
