# Generated by Django 6.0.5 on 2026-07-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitemcancellation_order_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitemcancellation',
            table='order_item_cancellation',
        ),
    ]
