# Generated by Django 6.0.5 on 2026-07-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_orderitemcancellation_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemcancellation",
            name="order_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation",
                to="order.orderitems",
            ),
        ),
    ]
