# Generated by Django 6.0.5 on 2026-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_orderreturns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order placed', 'Order Placed'), ('shipped', 'Shipped'), ('out for delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return pending', 'Return Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order placed', 'Order Placed'), ('shipped', 'Shipped'), ('out for delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return pending', 'Return Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255),
        ),
    ]
