# Generated by Django 6.0.5 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0020_orderitemreturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("return pending", "Return Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
