# Generated by Django 6.0.5 on 2026-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0023_orders_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
