# Generated by Django 6.0.5 on 2026-09-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_orders_coupon_code_orders_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='subtoal',
            new_name='subtotal',
        ),
    ]
