# Generated by Django 6.0.5 on 2026-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_users_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
