# Generated by Django 6.0.5 on 2026-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
