# Generated by Django 6.0.5 on 2026-05-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_users_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="status",
        ),
    ]
