# Generated by Django 6.0.5 on 2026-05-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_emailotp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailotp',
            table='email_otp',
        ),
    ]
