# Generated by Django 6.0.5 on 2026-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
