# Generated by Django 6.0.5 on 2026-05-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_emailotp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
