# Generated by Django 6.0.5 on 2026-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_emailotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(),
        ),
    ]
