# Generated by Django 6.0.5 on 2026-05-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_users_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
    ]
