# Generated by Django 6.0.5 on 2026-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_users_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
