# Generated by Django 6.0.5 on 2026-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_emailotp_email_alter_emailotp_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
