# Generated by Django 6.0.5 on 2026-05-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_users_password_hash_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
