# Generated by Django 6.0.5 on 2026-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar_url',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
