# Generated by Django 6.0.5 on 2026-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("refund", "Refund"),
                ],
                max_length=10,
            ),
        ),
    ]
