# Generated by Django 6.0.5 on 2026-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_wallettransaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
