# Generated by Django 6.0.5 on 2026-06-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_products_productvariant_productimage"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productimage",
            table="productimage",
        ),
        migrations.AlterModelTable(
            name="products",
            table="products",
        ),
        migrations.AlterModelTable(
            name="productvariant",
            table="productvariant",
        ),
    ]
