# Generated by Django 6.0.5 on 2026-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productimage_table_alter_products_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
