# Generated by Django 6.0.5 on 2026-06-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productimage_is_active_productvariant_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="is_active",
        ),
    ]
