# Generated by Django 6.0.5 on 2026-06-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
