# Generated by Django 6.0.5 on 2026-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='head',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
