# Generated by Django 6.0.5 on 2026-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='head',
            new_name='title',
        ),
    ]
