# Generated by Django 6.0.5 on 2026-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_rename_head_review_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
