# Generated by Django 6.0.5 on 2026-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productvariant_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
